! CSP450 Stage 4 - Walid branch FRRouting configuration
! Router: whansary-router

conf t
hostname whansary-router
no ip route 0.0.0.0/0 ens33
no ip route 172.16.101.0/26 192.168.6.81

interface ens37
 ip ospf network point-to-point
exit

router ospf
 ospf router-id 4.0.4.4
 network 10.33.0.0/16 area 0.0.0.0
 network 192.168.6.80/30 area 0.0.0.0
 default-information originate
exit

end
write memory
exit
